---
apiVersion: v1
kind: List
items:
- kind: ReplicationController
  apiVersion: v1
  metadata:
    name: webhook
  spec:
    replicas: 1
    selector:
      infra: webhook
    template:
      metadata:
        name: webhook
        labels:
          infra: webhook
      spec:
        containers:
          - name: amqp
            image: cockpit/amqp
            ports:
            - containerPort: 5671
              protocol: TCP
              name: amqp
            - containerPort: 5672
              protocol: TCP
              name: amqp
            volumeMounts:
            - name: webhook-secrets
              mountPath: /run/secrets/webhook
              readOnly: true
          - name: webhook
            image: cockpit/tasks
            ports:
              - containerPort: 8080
                protocol: TCP
            command: [ "webhook" ]
            volumeMounts:
            - name: webhook-secrets
              mountPath: /run/secrets/webhook
              readOnly: true
        volumes:
        - name: webhook-secrets
          secret:
            secretName: webhook-secrets
        serviceAccountName: create-job

- kind: Service
  apiVersion: v1
  metadata:
    name: webhook
  spec:
    clusterIP: None
    selector:
      infra: webhook
    ports:
    - name: webhook
      port: 80
      targetPort: 8080
      protocol: TCP

- kind: Route
  apiVersion: v1
  metadata:
    name: webhook
  spec:
    to:
      kind: Service
      name: webhook
    port:
      targetPort: 8080

- kind: Service
  apiVersion: v1
  metadata:
    name: amqp
  spec:
    clusterIP: None
    selector:
      infra: webhook
    ports:
    - targetPort: 5671
      port: 5671
      protocol: TCP
      name: amqp
    - targetPort: 5672
      port: 5672
      protocol: TCP
      name: amqp

- kind: Route
  apiVersion: v1
  metadata:
    name: amqp
  spec:
    to:
      kind: Service
      name: amqp
    port:
      targetPort: 5671
    tls:
      termination: passthrough
